<Project>
    <PropertyGroup>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>
